language: go

services:
    - mysql

go:
    - "1.9"
    - "1.10"
    - "1.11"

os:
  - linux

dist: trusty
sudo: false

install: true

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
