name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # Make sure the version is a string

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
      env:
        MARIADB_HOST: localhost
        MARIADB_USER: testuser
        MARIADB_PASSWORD: testpass
        MARIADB_DBNAME: testdb
        MARIADB_PORT: 3306
